<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <Platforms>x64</Platforms>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\AFOCS.Communication\AFOCS.Communication.csproj" />
    <ProjectReference Include="..\AFOCS.Core\AFOCS.Core.csproj" />
    <ProjectReference Include="..\AFOCS.Infrastructure\AFOCS.Infrastructure.csproj" />
    <ProjectReference Include="..\AFOCS.Shared\AFOCS.Shared.csproj" />
  </ItemGroup>
    <ItemGroup>
        <PackageReference Include="NationalInstruments.Visa" />
    </ItemGroup>
    <ItemGroup>
        <Reference Include="MvCameraControl.Net">
            <HintPath>..\Vendor\Camera\win64\MvCameraControl.Net.dll</HintPath>
        </Reference>
      
    </ItemGroup>

    <Target Name="CopyLTDMCDll" BeforeTargets="Build">
        <PropertyGroup>
            <SolutionDir>$(SolutionDir)</SolutionDir>
            <SourceDllPath>$(SolutionDir)Vendor\MotionCard\dll64\LTDMC.dll</SourceDllPath>
            <TargetDir>$(MainOutput)</TargetDir>
        </PropertyGroup>
        <Copy SourceFiles="$(SourceDllPath)" DestinationFolder="$(TargetDir)" SkipUnchangedFiles="true" OverwriteReadOnlyFiles="true" Condition="Exists('$(SourceDllPath)')" />
    </Target>

    <Target Name="CopyIspBoardll" BeforeTargets="Build">
        <PropertyGroup>
            <SolutionDir>$(SolutionDir)</SolutionDir>
            <SourceDllPaths>
                $(SolutionDir)Vendor\ISPBoard\dll64\CH375DLL.dll;
                $(SolutionDir)Vendor\ISPBoard\dll64\FOL_MsgCodes.dll;
                $(SolutionDir)Vendor\ISPBoard\dll64\RdOpticalDutInterface_LV2019_64b.dll;
            </SourceDllPaths>
            <TargetDir>$(MainOutput)</TargetDir>
        </PropertyGroup>
        <Copy SourceFiles="$(SourceDllPaths)" DestinationFolder="$(TargetDir)" SkipUnchangedFiles="true" OverwriteReadOnlyFiles="true" Condition="Exists('$(SolutionDir)Vendor\ISPBoard\dll64\CH375DLL.dll')  Or&#xD;&#xA;            Exists('$(SolutionDir)Vendor\ISPBoard\dll64\FOL_MsgCodes.dll') Or&#xD;&#xA;            Exists('$(SolutionDir)Vendor\ISPBoard\dll64\RdOpticalDutInterface_LV2019_64b.dll')" />
    </Target>
</Project>
