<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <Platforms>x64</Platforms>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Configs\**" />
    <EmbeddedResource Remove="Configs\**" />
    <None Remove="Configs\**" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AFOCS.Communication\AFOCS.Communication.csproj" />
    <ProjectReference Include="..\AFOCS.Core\AFOCS.Core.csproj" />
    <ProjectReference Include="..\AFOCS.Infrastructure\AFOCS.Infrastructure.csproj" />
    <ProjectReference Include="..\AFOCS.Shared\AFOCS.Shared.csproj" />
  </ItemGroup>
    <ItemGroup>
        <PackageReference Include="Agito.AAMotion" />
        <PackageReference Include="NationalInstruments.Visa" />
    </ItemGroup>
    <ItemGroup>
        <Reference Include="MvCameraControl.Net">
            <HintPath>..\Vendor\Camera\win64\MvCameraControl.Net.dll</HintPath>
        </Reference>
      
    </ItemGroup>

    <Target Name="CopyLTDMCDll" BeforeTargets="Build">
        <PropertyGroup>
            <SolutionDir>$(SolutionDir)</SolutionDir>
            <SourceDllPath>$(SolutionDir)Vendor\MotionCard\dll64\LTDMC.dll</SourceDllPath>
            <TargetDir>$(MainOutput)</TargetDir>
        </PropertyGroup>
        <Copy SourceFiles="$(SourceDllPath)" DestinationFolder="$(TargetDir)" SkipUnchangedFiles="true" OverwriteReadOnlyFiles="true" Condition="Exists('$(SourceDllPath)')" />
    </Target>

    <Target Name="CopyIspBoardll" BeforeTargets="Build">
        <PropertyGroup>
            <SolutionDir>$(SolutionDir)</SolutionDir>
        </PropertyGroup>
        <Copy SourceFiles="$(SolutionDir)Vendor\ISPBoard\dll64\CH375DLL.dll" DestinationFolder="$(MainOutput)" SkipUnchangedFiles="true" OverwriteReadOnlyFiles="true" Condition="Exists('$(SolutionDir)Vendor\ISPBoard\dll64\CH375DLL.dll')" />
        <Copy SourceFiles="$(SolutionDir)Vendor\ISPBoard\dll64\FOL_MsgCodes.dll" DestinationFolder="$(MainOutput)" SkipUnchangedFiles="true" OverwriteReadOnlyFiles="true" Condition="Exists('$(SolutionDir)Vendor\ISPBoard\dll64\FOL_MsgCodes.dll')" />
        <Copy SourceFiles="$(SolutionDir)Vendor\ISPBoard\dll64\RdOpticalDutInterface_LV2019_64b.dll" DestinationFolder="$(MainOutput)" SkipUnchangedFiles="true" OverwriteReadOnlyFiles="true" Condition="Exists('$(SolutionDir)Vendor\ISPBoard\dll64\RdOpticalDutInterface_LV2019_64b.dll')" />
        <Copy SourceFiles="$(SolutionDir)ISPBoard\x64\$(Configuration)\ISPBoard.dll" DestinationFolder="$(MainOutput)" SkipUnchangedFiles="true" OverwriteReadOnlyFiles="true" Condition="Exists('$(SolutionDir)ISPBoard\x64\$(Configuration)\ISPBoard.dll')" />
    </Target>
</Project>
