<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="..\..\..\Users\Administrator\Desktop\InputImg.jpeg" Link="Images\InputImg.jpeg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="..\..\..\Users\Administrator\Desktop\Model.jpeg" Link="Images\Model.jpeg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Emgu.CV" />
    <PackageReference Include="Emgu.CV.Bitmap" />
    <PackageReference Include="Emgu.CV.runtime.windows" />
    <PackageReference Include="Emgu.CV.Wpf" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Images\" />
  </ItemGroup>

</Project>
