<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0-windows7.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <Platforms>x64</Platforms>
      <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Advance\**" />
    <Compile Remove="Converters\**" />
    <Compile Remove="ViewModels\Test\**" />
    <Compile Remove="Views\DeviceConfig\**" />
    <Compile Remove="Views\Test\**" />
    <EmbeddedResource Remove="Advance\**" />
    <EmbeddedResource Remove="Converters\**" />
    <EmbeddedResource Remove="ViewModels\Test\**" />
    <EmbeddedResource Remove="Views\DeviceConfig\**" />
    <EmbeddedResource Remove="Views\Test\**" />
    <None Remove="Advance\**" />
    <None Remove="Converters\**" />
    <None Remove="ViewModels\Test\**" />
    <None Remove="Views\DeviceConfig\**" />
    <None Remove="Views\Test\**" />
    <Page Remove="Advance\**" />
    <Page Remove="Converters\**" />
    <Page Remove="ViewModels\Test\**" />
    <Page Remove="Views\DeviceConfig\**" />
    <Page Remove="Views\Test\**" />
  </ItemGroup>
    <ItemGroup>
        <ApplicationDefinition Remove="App.xaml" />
        <PackageReference Include="Caliburn.Micro" />
        <PackageReference Include="MahApps.Metro" />
        <PackageReference Include="Serilog" />
        <PackageReference Include="Serilog.Sinks.Console" />

        <Page Include="App.xaml" />
    </ItemGroup>
    <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|x64' ">
        <OutputPath>$(MainOutput)\</OutputPath>
        <WarningLevel>3</WarningLevel>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    </PropertyGroup>

    <!--<PropertyGroup>
        <ApplicationIcon>favicon.ico</ApplicationIcon>
    </PropertyGroup>-->
    <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|x64' ">
        <OutputPath>$(MainOutput)\</OutputPath>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\AFOCS.Communication\AFOCS.Communication.csproj" />
      <ProjectReference Include="..\AFOCS.Core\AFOCS.Core.csproj" />
      <ProjectReference Include="..\AFOCS.Devices\AFOCS.Devices.csproj" />
      <ProjectReference Include="..\AFOCS.Framework\AFOCS.Framework.csproj" />
      <ProjectReference Include="..\AFOCS.Infrastructure\AFOCS.Infrastructure.csproj" />
        <ProjectReference Include="..\AFOCS.FlowNodeEditor\AFOCS.FlowNodeEditor.csproj" />
        <ProjectReference Include="..\ISPBoard\ISPBoard.vcxproj" />
    </ItemGroup>
    <ItemGroup>
      <Reference Include="MvCameraControl.Net">
        <HintPath>..\Vendor\Camera\win64\MvCameraControl.Net.dll</HintPath>
      </Reference>
    </ItemGroup>
</Project>
