<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0-windows7.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <Platforms>x64</Platforms>
      <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Advance\" />
    <Folder Include="Converters\" />
    <Folder Include="ViewModels\Test\" />
    <Folder Include="Views\DeviceConfig\" />
    <Folder Include="Views\Test\" />
  </ItemGroup>
    <ItemGroup>
        <ApplicationDefinition Remove="App.xaml" />
        <PackageReference Include="Caliburn.Micro" />
        <PackageReference Include="MahApps.Metro" />
        <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
        <PackageReference Include="Microsoft.Extensions.Logging" />
        <PackageReference Include="Microsoft.Extensions.Logging.Console" />
        <PackageReference Include="NationalInstruments.Visa" />
        <PackageReference Include="System.IO.Ports" />
        <Page Include="App.xaml" />
    </ItemGroup>
    <ItemGroup>
      <ProjectReference Include="..\AFOCS.Framework\AFOCS.Framework.csproj" />
    </ItemGroup>
    <ItemGroup>
      <Reference Include="MvCameraControl.Net">
        <HintPath>..\Vendor\Camera\win64\MvCameraControl.Net.dll</HintPath>
      </Reference>
    </ItemGroup>
</Project>
